/*
Instituto Tecnológico de Costa Rica
Esto corresponde al Parser del compilador e.e

Nombre archivo: parser.cup
Para crear: java java_cup.Main< ycalc.cup
            el .jar de cup debe estar en el mismo directorio

Manual de cup http://www.cs.princeton.edu/~appel/modern/java/CUP/manual.html#intro
 ver el archivo ycal.cup en jflex... examples
*/

// Se requiere de la clase java_cup.runtime.* 
import java_cup.runtime.*;

/*------------- Código del Parser -------------*/






/*------------- Declaración de los Terminales y No Terminales ------------- */

terminal +,-, class

non terminal <archivo_codigo>, <funciones>, <variables>, <programa_principal>, <bloque_codigo>, <identificador>, <parametros>


/*------------- Declaración de Precedencia y Asociatividad -------------*/

<archivo_codigo> ::= <funciones> <variables> <programa_principal> 
                     | class <identificador> : <variables> <metodos> <var_globales> <programa_principal>

<funciones> ::= def <identificador> (<parametros>): <variables> < bloque_funcion>

<variables> ::= int <identificador> <variables> 
               | string <identificador> <variables>
/* faltan los demas tipos de variables y el enter o terminador */

