package proyectocompi.parser;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 29 23:11:36 CST 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int string = 12;
  public static final int INT = 9;
  public static final int PLUS = 2;
  public static final int RPAREN = 5;
  public static final int EQUAL = 6;
  public static final int CATCH = 23;
  public static final int elif = 20;
  public static final int LPAREN = 4;
  public static final int TRY = 22;
  public static final int in = 17;
  public static final int FINALLY = 24;
  public static final int CLASS = 7;
  public static final int def = 8;
  public static final int range = 18;
  public static final int IF = 19;
  public static final int EOF = 0;
  public static final int WHILE = 15;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int ELSE = 21;
  public static final int FOR = 16;
  public static final int list = 11;
  public static final int CHAR = 14;
  public static final int BOOLEAN = 13;
  public static final int FLOAT = 10;
}

