
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 02 02:36:31 CST 2016
//----------------------------------------------------
package proyectocompi.parser;
/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int error = 1;
  public static final int def = 2;
  public static final int EOF = 0;
}

