/* The following code was generated by JFlex 1.6.1 */

package proyectocompi.jflex;
import static proyectocompi.jflex.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/esporras/Documents/NetBeansProjects/ProyectoCompi/src/proyectocompi/jflex/Lexer.flex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\12\0\1\13\1\56\1\56\1\56\22\0\1\52\1\44\1\55\2\0"+
    "\1\42\1\47\1\54\1\53\1\53\1\6\1\11\1\50\1\3\1\7"+
    "\1\41\12\2\1\51\1\0\1\45\1\43\1\46\2\0\4\1\1\10"+
    "\4\1\1\12\1\1\1\5\16\1\1\1\1\1\1\1\1\1\2\1"+
    "\1\14\1\21\1\23\1\31\1\16\1\32\1\36\1\40\1\27\1\12"+
    "\1\22\1\24\1\35\1\26\1\25\1\33\1\1\1\17\1\15\1\20"+
    "\1\30\1\1\1\37\1\4\1\34\1\1\1\53\1\47\1\53\1\47"+
    "\6\0\1\56\u05da\0\12\2\206\0\12\2\306\0\12\2\u019c\0\12\2"+
    "\166\0\12\2\166\0\12\2\166\0\12\2\166\0\12\2\166\0\12\2"+
    "\166\0\12\2\166\0\12\2\166\0\12\2\166\0\12\2\140\0\12\2"+
    "\166\0\12\2\106\0\12\2\u0116\0\12\2\106\0\12\2\u0746\0\12\2"+
    "\46\0\12\2\u012c\0\12\2\200\0\12\2\246\0\12\2\6\0\12\2"+
    "\266\0\12\2\126\0\12\2\206\0\12\2\6\0\12\2\u03ce\0\1\56"+
    "\1\56\u85f6\0\12\2\u02a6\0\12\2\46\0\12\2\306\0\12\2\26\0"+
    "\12\2\126\0\12\2\u0196\0\12\2\u5316\0\12\2\u0586\0\12\2\u0bbc\0"+
    "\12\2\200\0\12\2\74\0\12\2\220\0\12\2\u0116\0\12\2\u01d6\0"+
    "\12\2\u0176\0\12\2\146\0\12\2\u0216\0\12\2\u5176\0\12\2\346\0"+
    "\12\2\u6c74\0\62\2\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u280f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\1\1\1\4\1\5"+
    "\20\2\1\4\1\6\1\1\2\7\1\10\1\11\1\12"+
    "\1\5\1\13\2\1\1\0\1\14\1\0\1\15\1\0"+
    "\1\3\1\0\1\6\14\0\1\16\1\0\1\17\1\20"+
    "\13\0\1\7\1\21\1\0\1\22\1\0\1\22\1\3"+
    "\1\0\1\15\1\23\2\0\1\15\25\0\1\22\2\0"+
    "\1\15\1\0\1\3\1\15\13\0\2\15\1\0\1\15"+
    "\7\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\57\0\136\0\215\0\274\0\353\0\u011a"+
    "\0\57\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263"+
    "\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db"+
    "\0\u040a\0\u0439\0\u0468\0\u0468\0\u0497\0\u04c6\0\57\0\57"+
    "\0\57\0\u04f5\0\57\0\u0524\0\u0553\0\u0582\0\57\0\u05b1"+
    "\0\u05e0\0\u060f\0\u063e\0\353\0\57\0\u066d\0\u069c\0\u06cb"+
    "\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843"+
    "\0\u0872\0\57\0\u08a1\0\57\0\57\0\u08d0\0\u08ff\0\u092e"+
    "\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6"+
    "\0\57\0\57\0\u0ad5\0\u0b04\0\u0553\0\u0553\0\u0582\0\u0b33"+
    "\0\u0b62\0\57\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c"+
    "\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67\0\u0d96\0\u0dc5\0\u0df4"+
    "\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c"+
    "\0\u0f9b\0\u0fca\0\57\0\u0ff9\0\u1028\0\u1057\0\u1086\0\u10b5"+
    "\0\u10e4\0\u1113\0\u1142\0\u1171\0\u11a0\0\u11cf\0\u11fe\0\u122d"+
    "\0\u125c\0\u128b\0\u12ba\0\u12e9\0\u1318\0\u1347\0\u1376\0\u13a5"+
    "\0\u13d4\0\u1403\0\u1432\0\u1461\0\u1490\0\u14bf\0\u14ee";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\2\3\1\6\1\7\1\3"+
    "\1\10\1\3\1\11\1\12\1\3\1\13\1\14\1\15"+
    "\1\16\1\3\1\17\1\20\1\21\1\22\1\23\1\3"+
    "\1\24\1\25\1\26\1\27\1\3\1\30\1\31\1\3"+
    "\1\32\1\10\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\62\0\1\4\1\0"+
    "\1\46\1\47\1\50\1\51\1\52\5\0\1\52\42\0"+
    "\1\53\4\0\1\54\33\0\1\55\21\0\1\10\34\0"+
    "\1\55\15\0\1\56\117\0\1\55\30\0\1\57\10\0"+
    "\1\60\34\0\1\61\17\0\1\62\46\0\1\63\1\0"+
    "\1\64\57\0\1\65\56\0\1\66\63\0\1\67\1\70"+
    "\45\0\1\71\61\0\1\72\64\0\1\73\46\0\1\74"+
    "\10\0\1\74\3\0\1\75\2\0\1\76\37\0\1\77"+
    "\57\0\1\100\5\0\1\101\1\0\1\102\43\0\1\103"+
    "\2\0\1\104\66\0\1\105\53\0\1\106\61\0\1\107"+
    "\10\0\1\110\57\0\1\10\1\0\1\55\56\0\1\111"+
    "\56\0\1\111\1\0\1\37\1\111\53\0\1\111\2\0"+
    "\1\37\62\0\1\112\4\0\54\113\1\114\2\113\54\115"+
    "\1\0\1\116\1\115\2\0\1\117\56\0\1\120\56\0"+
    "\1\121\7\0\1\122\47\0\1\123\5\0\1\123\47\0"+
    "\1\53\1\0\1\124\1\47\1\0\1\125\51\0\1\56"+
    "\1\126\4\0\1\127\1\126\1\122\3\0\1\127\55\0"+
    "\1\130\72\0\1\72\43\0\1\131\4\0\1\132\50\0"+
    "\1\133\11\0\1\134\56\0\1\135\47\0\1\136\72\0"+
    "\1\75\40\0\1\137\54\0\1\103\70\0\1\140\65\0"+
    "\1\141\41\0\1\72\71\0\1\142\47\0\1\75\5\0"+
    "\1\75\51\0\1\143\50\0\1\75\65\0\1\144\45\0"+
    "\1\145\70\0\1\146\45\0\1\147\65\0\1\150\51\0"+
    "\1\151\65\0\1\152\27\0\54\113\1\153\2\113\54\0"+
    "\1\154\4\0\1\120\2\0\1\47\53\0\1\121\1\155"+
    "\4\0\1\156\1\155\1\122\3\0\1\156\42\0\1\157"+
    "\56\0\1\160\56\0\1\161\7\0\1\122\46\0\1\157"+
    "\5\0\1\123\5\0\1\123\43\0\1\123\5\0\1\123"+
    "\1\122\62\0\1\162\63\0\1\75\51\0\1\163\56\0"+
    "\1\75\72\0\1\75\41\0\1\133\71\0\1\164\42\0"+
    "\1\165\62\0\1\166\57\0\1\167\62\0\1\162\66\0"+
    "\1\75\35\0\1\170\57\0\1\75\67\0\1\171\54\0"+
    "\1\172\53\0\1\173\75\0\1\75\42\0\1\133\32\0"+
    "\54\154\1\174\2\154\10\0\1\175\5\0\1\175\42\0"+
    "\1\176\1\123\5\0\1\123\1\122\46\0\1\157\7\0"+
    "\1\122\46\0\1\160\2\0\1\47\53\0\1\161\1\177"+
    "\4\0\1\200\1\177\1\122\3\0\1\200\57\0\1\171"+
    "\72\0\1\171\42\0\1\201\61\0\1\75\63\0\1\202"+
    "\60\0\1\203\51\0\1\204\52\0\1\75\67\0\1\75"+
    "\41\0\1\205\116\0\1\206\4\0\1\175\56\0\1\176"+
    "\7\0\1\122\54\0\1\176\5\0\1\176\42\0\1\175"+
    "\7\0\1\122\72\0\1\75\56\0\1\207\44\0\1\75"+
    "\66\0\1\65\56\0\1\75\106\0\1\153\32\0\1\133"+
    "\26\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5405];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\5\1\1\11\25\1\3\11\1\1\1\11"+
    "\2\1\1\0\1\11\1\0\1\1\1\0\1\1\1\0"+
    "\1\11\14\0\1\11\1\0\2\11\13\0\2\11\1\0"+
    "\1\1\1\0\2\1\1\0\1\1\1\11\2\0\1\1"+
    "\25\0\1\11\2\0\1\1\1\0\2\1\13\0\2\1"+
    "\1\0\1\1\7\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public String lexeme;
    public int linea() {return yyline+1;}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 378) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return ERROR;
            }
          case 20: break;
          case 2: 
            { lexeme=yytext(); return Variable;
            }
          case 21: break;
          case 3: 
            { lexeme=yytext(); return Numero_Entero;
            }
          case 22: break;
          case 4: 
            { lexeme=yytext(); return operador_aritmetico;
            }
          case 23: break;
          case 5: 
            { /*Ignore*/
            }
          case 24: break;
          case 6: 
            { lexeme=yytext(); return operador_asignativo;
            }
          case 25: break;
          case 7: 
            { lexeme=yytext(); return operador_comparativo;
            }
          case 26: break;
          case 8: 
            { lexeme=yytext(); return operador_bits;
            }
          case 27: break;
          case 9: 
            { lexeme=yytext(); return separador_coma;
            }
          case 28: break;
          case 10: 
            { lexeme=yytext(); return separador_dos_puntos;
            }
          case 29: break;
          case 11: 
            { lexeme=yytext(); return contenedor;
            }
          case 30: break;
          case 12: 
            { lexeme=yytext(); return Numero_Long;
            }
          case 31: break;
          case 13: 
            { lexeme=yytext(); return Numero_Flotante;
            }
          case 32: break;
          case 14: 
            { lexeme=yytext(); return operador_logico;
            }
          case 33: break;
          case 15: 
            { lexeme=yytext(); return comparador_identidad;
            }
          case 34: break;
          case 16: 
            { lexeme=yytext(); return palabra_reservada;
            }
          case 35: break;
          case 17: 
            { lexeme=yytext(); return separador_tab;
            }
          case 36: break;
          case 18: 
            { lexeme=yytext(); return literal_string;
            }
          case 37: break;
          case 19: 
            { lexeme=yytext(); return Numero_Complejo;
            }
          case 38: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
